### ISSUE TITLE
`perf list` event name change

### ISSUE THREAD

**Issue by warsier** [rutgers-apl/TaskProf#1]
`build.sh` detects the "cpu-cycles" event exists or not and decides whether to compile or not. Yet the name of PMU event seems to be changed to "cpu-cycles OR cpu/cpu-cycles" on a Xeon E5 machine which runs Ubuntu 16.04.

**Comment by adarshyoga** [comment]
On the machines we tested on, "cpu-cycles OR cpu/cpu-cycles" is listed as a "Kernel PMU Event".
      --- cpu-cycles OR cpu/cpu-cycles/                      [Kernel PMU event]
TaskProf specifically uses "cpu-cycles" hardware event and not kernel PMU event. Hence the `build.sh` script checks for "cpu-cycles OR cycles" which is listed by `perf list` as a hardware event.
      --- cpu-cycles OR cycles                               [Hardware event]
Can you please verify if "cpu-cycles OR cpu/cpu-cycles" is listed as a "Hardware event" on your machine?

**Comment by warsier** [comment]
Thank you. 
I actually did not notice the difference between [Kernel PMU event] and [Hardware event].
And yes, there was no corresponding --- cpu-cycles OR cycles  [Hardware event].
So I guess this CPU does not support this hardware event.

**Comment by adarshyoga** [comment]
Most likely your machine supports hardware events, but it may not be "enabled". To check if it is enabled use,
> cat /proc/sys/kernel/perf_event_paranoid

This should output 1. If not, hardware events are not "enabled". To enable it, you can use

> sudo sh -c 'echo 1 > /proc/sys/kernel/perf_event_paranoid'

And then you can check `perf list`, which will show "cpu-cycles OR cycles [Hardware event]".

**Comment by warsier** [comment]
Thank you so much! The problem was solved.
