### ISSUE TITLE
Delaunay Triangulation not getting parallelism as expected.

### ISSUE THREAD

**Issue by warsier** [rutgers-apl/TaskProf#2]
We tried to reproduce the results using the benchmark provided, and got similar results as described in the paper except for `Delaunay Triangulation`. The annotated regions show almost no parallelism. The output is as follows:

region_info.csv:
```
4228347,IO.h,184
4228158,IO.h,176
4227901,IO.h,159
4227424,IO.h,184
4227218,IO.h,176
4226941,IO.h,159
4254744,delaunay.C,275
4254603,delaunay.C,263
4206013,IO.h,89 
```

region_all.csv:
```
Regions Optimization factor, Whole program parallelism
50,1.75187
100,1.75639
200,1.75866 
400,1.7598 
```

**Comment by adarshyoga** [comment]
For `Delaunay triangulation` the regions that need to be annotated are,
```
delaunay.C - line 225 to 243
delaunay.C - line 326 to 344
delaunay.C - line 360 to 363
IO.h - line 88 to 89
IO.h - line 172 to 186
```
If these regions are annotated, region_all.csv will show an improvement in parallelism from 1.75 to ~50.
